export const OrganImageFlash = {
    // --- SYSTEM CIRCULATORY ---
    'Cor': require('../../assets/heart.png'),
    'Pulmo': require('../../assets/sistem_peredaran_darah/paru-paru.png'),
    'Arteria': require('../../assets/sistem_peredaran_darah/pembuluh-nadi.png'),
    'Vena': require('../../assets/sistem_peredaran_darah/pembuluh-balik.png'),
    'Capillus': require('../../assets/sistem_peredaran_darah/pembuluh-rambut.png'),
    'Aorta': require('../../assets/sistem_peredaran_darah/aorta.png'),
    'Eritrosit': require('../../assets/sistem_peredaran_darah/sel-darah-merah.png'),
    'Leukosit': require('../../assets/sistem_peredaran_darah/sel-darah-putih.png'),
    'Trombosit': require('../../assets/sistem_peredaran_darah/keping-darah.png'),
    'Plasma Sanguinis': require('../../assets/sistem_peredaran_darah/plasma-sanguinis.png'),
    'Atrium': require('../../assets/sistem_peredaran_darah/serambi-jantung.png'),
    'Ventriculus Cordis': require('../../assets/sistem_peredaran_darah/bilik-jantung.png'),
    'Valvula': require('../../assets/sistem_peredaran_darah/katup jantung.png'),
    'Pericardium': require('../../assets/sistem_peredaran_darah/selaput-pembungkus-jantung.png'),
    'Myocardium': require('../../assets/sistem_peredaran_darah/lapisan-otot-jantung.png'),

    // --- SYSTEM RESPIRATORY ---
    'Cavum Nasalis': require('../../assets/sistem_pernapasan/rongga-hidung.png'),
    'Laring': require('../../assets/sistem_pernapasan/pangkal-tenggorokan.png'),
    'Trakea': require('../../assets/sistem_pernapasan/batang tenggorokan.png'),
    'Bronkus': require('../../assets/sistem_pernapasan/cabang tenggorokan.png'),
    'Bronkiolus': require('../../assets/sistem_pernapasan/ranting tenggorokan.png'),
    'Alveolus': require('../../assets/sistem_pernapasan/alveolus.png'),
    'Epiglottis': require('../../assets/sistem_pernapasan/epiglottis.png'),
    'Plica Vocalis': require('../../assets/sistem_pernapasan/pita-suara.png'),
    'Pleura': require('../../assets/sistem_pernapasan/selaput_paru.png'),
    'Diaphragma': require('../../assets/sistem_pernapasan/diaphragma.png'),
    'Sinus Paranasal': require('../../assets/sistem_pernapasan/sinus-paranasal.png'),
    'Faring': require('../../assets/sistem_pernapasan/faring.png'),
    'Nasofaring': require('../../assets/sistem_pernapasan/nasofaring.png'),

    // --- SYSTEM DIGESTIVE ---
    'Cavum Oris': require('../../assets/pencernaan/rongga-mulut.png'),
    'Esophagus': require('../../assets/pencernaan/kerongkongan.png'),
    'Gaster': require('../../assets/pencernaan/lambung.png'),
    'Intestinum Tenue': require('../../assets/pencernaan/usus-halus.png'),
    'Duodenum': require('../../assets/pencernaan/duodenum.png'),
    'Jejunum': require('../../assets/pencernaan/jejunum.png'),
    'Ileum': require('../../assets/pencernaan/ileum.png'),
    'Intestinum Crassum': require('../../assets/pencernaan/usus-besar.png'),
    'Pancreas': require('../../assets/pencernaan/empedu.png'),
    'Cecum': require('../../assets/pencernaan/cecum.png'),
    'Appendix': require('../../assets/pencernaan/umbai-cacing.png'),
    'Rectum': require('../../assets/pencernaan/rectum.png'),
    'Anus': require('../../assets/pencernaan/anus.png'),
    'Hepar / Liver': require('../../assets/pencernaan/liver.png'),
    'Vesica Fellea': require('../../assets/pencernaan/empedu.png'),
    'Glandula Salivaria': require('../../assets/pencernaan/kelenjar-ludah.png'),
    'Glandula Parotis': require('../../assets/pencernaan/ludah-telinga.png'),
    'Lingua': require('../../assets/pencernaan/lidah.png'),
    'Dentes': require('../../assets/pencernaan/gigi.png'),
    'Dentes Incisivi': require('../../assets/pencernaan/gigi-seri.png'),
    'Dentes Canini': require('../../assets/pencernaan/gigi-taring.png'),
    'Dentes Premolares': require('../../assets/pencernaan/geraham-kecil.png'),
    'Dentes Molares': require('../../assets/pencernaan/geraham-besar.png'),
    'Email': require('../../assets/pencernaan/email.png'),
    'Dentin': require('../../assets/pencernaan/tulang-gigi.png'),
    'Pulpa': require('../../assets/pencernaan/rongga-gigi.png'),
    'Vili': require('../../assets/pencernaan/lipatan-usus.png'),
    
};
