export const OrganImageFlash = {
    // --- SYSTEM CIRCULATORY ---
    'Cor': require('../../assets/heart.png'),
    'Pulmo': require('../../assets/sistem_peredaran_darah/paru-paru.png'),
    'Arteria': require('../../assets/sistem_peredaran_darah/pembuluh-nadi.png'),
    'Vena': require('../../assets/sistem_peredaran_darah/pembuluh-balik.png'),
    'Capillus': require('../../assets/sistem_peredaran_darah/pembuluh-rambut.png'),
    'Aorta': require('../../assets/sistem_peredaran_darah/aorta.png'),
    'Eritrosit': require('../../assets/sistem_peredaran_darah/sel-darah-merah.png'),
    'Leukosit': require('../../assets/sistem_peredaran_darah/sel-darah-putih.png'),
    'Trombosit': require('../../assets/sistem_peredaran_darah/keping-darah.png'),
    'Plasma Sanguinis': require('../../assets/sistem_peredaran_darah/plasma-sanguinis.png'),
    'Atrium': require('../../assets/sistem_peredaran_darah/serambi-jantung.png'),
    'Ventriculus Cordis': require('../../assets/sistem_peredaran_darah/bilik-jantung.png'),
    'Valvula': require('../../assets/sistem_peredaran_darah/katup jantung.png'),
    'Pericardium': require('../../assets/sistem_peredaran_darah/selaput-pembungkus-jantung.png'),
    'Myocardium': require('../../assets/sistem_peredaran_darah/lapisan-otot-jantung.png'),

    // --- SYSTEM RESPIRATORY ---
    'Cavum Nasalis': require('../../assets/sistem_pernapasan/rongga-hidung.png'),
    'Laring': require('../../assets/sistem_pernapasan/pangkal-tenggorokan.png'),
    'Trakea': require('../../assets/sistem_pernapasan/batang tenggorokan.png'),
    'Bronkus': require('../../assets/sistem_pernapasan/cabang tenggorokan.png'),
    'Bronkiolus': require('../../assets/sistem_pernapasan/ranting tenggorokan.png'),
    'Alveolus': require('../../assets/sistem_pernapasan/alveolus.png'),
    'Epiglottis': require('../../assets/sistem_pernapasan/epiglottis.png'),
    'Plica Vocalis': require('../../assets/sistem_pernapasan/pita-suara.png'),
    'Pleura': require('../../assets/sistem_pernapasan/selaput_paru.png'),
    'Diaphragma': require('../../assets/sistem_pernapasan/diaphragma.png'),
    'Sinus Paranasal': require('../../assets/sistem_pernapasan/sinus-paranasal.png'),
    'Faring': require('../../assets/sistem_pernapasan/faring.png'),
    'Nasofaring': require('../../assets/sistem_pernapasan/nasofaring.png'),

    // --- SYSTEM DIGESTIVES ---
    'Cavum Oris': require('../../assets/pencernaan/rongga-mulut.png'),
    'Esophagus': require('../../assets/pencernaan/kerongkongan.png'),
    'Gaster': require('../../assets/pencernaan/lambung.png'),
    'Intestinum Tenue': require('../../assets/pencernaan/usus-halus.png'),
    'Duodenum': require('../../assets/pencernaan/duodenum.png'),
    'Jejunum': require('../../assets/pencernaan/jejunum.png'),
    'Ileum': require('../../assets/pencernaan/ileum.png'),
    'Intestinum Crassum': require('../../assets/pencernaan/usus-besar.png'),
    'Pancreas': require('../../assets/pencernaan/empedu.png'),
    'Cecum': require('../../assets/pencernaan/cecum.png'),
    'Appendix': require('../../assets/pencernaan/umbai-cacing.png'),
    'Rectum': require('../../assets/pencernaan/rectum.png'),
    'Anus': require('../../assets/pencernaan/anus.png'),
    'Hepar / Liver': require('../../assets/pencernaan/liver.png'),
    'Vesica Fellea': require('../../assets/pencernaan/empedu.png'),
    'Glandula Salivaria': require('../../assets/pencernaan/kelenjar-ludah.png'),
    'Glandula Parotis': require('../../assets/pencernaan/ludah-telinga.png'),
    'Lingua': require('../../assets/pencernaan/lidah.png'),
    'Dentes': require('../../assets/pencernaan/gigi.png'),
    'Dentes Incisivi': require('../../assets/pencernaan/gigi-seri.png'),
    'Dentes Canini': require('../../assets/pencernaan/gigi-taring.png'),
    'Dentes Premolares': require('../../assets/pencernaan/geraham-kecil.png'),
    'Dentes Molares': require('../../assets/pencernaan/geraham-besar.png'),
    'Email': require('../../assets/pencernaan/email.png'),
    'Dentin': require('../../assets/pencernaan/tulang-gigi.png'),
    'Pulpa': require('../../assets/pencernaan/rongga-gigi.png'),
    'Vili': require('../../assets/pencernaan/lipatan-usus.png'),

    // --- SYSTEM SKELETAL ---
    'Cranium': require('../../assets/rangka/tengkorak.png'),
    'Femur': require('../../assets/rangka/tulang-paha.png'),
    'Tibia': require('../../assets/rangka/tulang-kering.png'),
    'Fibula': require('../../assets/rangka/fibula.png'),
    'Patella': require('../../assets/rangka/tulang-tempurung-lutut.png'),
    'Humerus': require('../../assets/rangka/tulang-lengan-atas.png'),
    'Radius': require('../../assets/rangka/pengumpil.png'),
    'Ulna': require('../../assets/rangka/hasta.png'),
    'Clavicula': require('../../assets/rangka/selangka.png'),
    'Scapula': require('../../assets/rangka/belikat.png'),
    'Sternum': require('../../assets/rangka/tulang-dada.png'),
    'Costae': require('../../assets/rangka/rusuk.png'),
    'Vertebrae': require('../../assets/rangka/tulang-belakang.png'),
    'Vertebrae Cervicales': require('../../assets/rangka/tulang-leher.png'),
    'Vertebrae Thoracales': require('../../assets/rangka/tulang-punggung.png'),
    'Vertebrae Lumbales': require('../../assets/rangka/tulang-pinggang.png'),
    'Sacrum': require('../../assets/rangka/tulang-kelangkang.png'),
    'Coccyx': require('../../assets/rangka/tulang-ekor.png'),
    'Pelvis': require('../../assets/rangka/tulang-panggul.png'),
    'Carpal': require('../../assets/rangka/tulang-pergelangan-tangan.png'),
    'Metacarpal': require('../../assets/rangka/tulang-telapak-tangan.png'),
    'Phalanges': require('../../assets/rangka/tulang-jari.png'),
    'Tarsal': require('../../assets/rangka/tulang-pergelangan-kaki.png'),
    'Metatarsal': require('../../assets/rangka/tulang-telapak-kaki.png'),
    'Cartilago': require('../../assets/rangka/tulang-rawan.png'),
    'Articulatio': require('../../assets/rangka/sendi.png'),
    'Sistem Havers': require('../../assets/rangka/struktur-silinder-tulang.png'),
    'Osteoblas': require('../../assets/rangka/sel-tulang-muda.png'),
    'Osteosit': require('../../assets/rangka/sel-tulang-dewasa.png'),
    'Osteoklas': require('../../assets/rangka/sel-perombak-tulang.png'),
    
    // --- SYSTEM MUSCULAR ---
    'Textus Muscularis': require('../../assets/otot/jaringan-otot.png'),
    'Textus Muscularis Nonstriatus': require('../../assets/otot/otot-polos.png'),
    'Textus Muscularis Striatus': require('../../assets/otot/otot-rangka.png'),
    'Tendon': require('../../assets/otot/tendon.png'),
    'Ligamentum': require('../../assets/otot/ligamentum.png'),
    'Fascia': require('../../assets/otot/fascia.png'),
    'Musculus Biceps Brachii': require('../../assets/otot/otot-lengan-atas-depan.png'),
    'Musculus Triceps Brachii': require('../../assets/otot/otot-lengan-atas-belakang.png'),
    'Musculus Pectoralis Major': require('../../assets/otot/otot-dada-besar.png'),
    'Musculus Deltoideus': require('../../assets/otot/otot-bahu.png'),
    'Musculus Latissimus Dorsi': require('../../assets/otot/otot-punggung-lebar.png'),
    'Musculus Gastrocnemius': require('../../assets/otot/otot-betis.png'),
    'Musculus Gluteus Maximus': require('../../assets/otot/otot-pantat-besar.png'),
    'Musculus Masseter': require('../../assets/otot/otot-kunyah.png'),

    // --- SYSTEM EKSKRETION ---
    'Ren / Kidney': require('../../assets/ekskresi/ginjal.png'),
    'Cutis': require('../../assets/ekskresi/kulit.png'),
    'Epidermis': require('../../assets/ekskresi/kulit-ari.png'),
    'Dermis': require('../../assets/ekskresi/dermis.png'),
    'Ureter': require('../../assets/ekskresi/ureter.png'),
    'Vesica Urinaria': require('../../assets/ekskresi/kantung-kemih.png'),
    'Urethra': require('../../assets/ekskresi/urethra.png'),
    'Glomerulus': require('../../assets/ekskresi/glomerulus.png'),
};
